server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tables?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

logging:
  level:
    root: info
    com.tzy: debug


fileServer:
  pathDirectory: D:/FileCenter/
  token: 3dsf43cvxe35cxdfg
  serverPrivateKey : MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCUMLdQdAHaHM72/Rho6eMQxPzBHpaBi7FZZaEY9GCveUXqvHiSEfvp0fnHgcvshRT5Ohmv4nQETbLsGz9qOlZfpY6GbI2466HoZ4DKooT5Xpp74nITDj5Tmq7OLpCWqt7y8mjB4Pdde1ystQxSTrOKiRQe3OlXKEPz4N2LYMhdiMARuN2v9REInN8sMHNLenIqYF/7wizfdc25ZtoeoDlZPdEOFj1AfifEU9XFI3U4B6EqjfETL7QiKcSQcKB3Z+PnLPSaNX0sRcZB3xEx40+/k62hpz35UJkPHyRgrLcElbYcdZGRizood9lulykf21LK8emjsv3qD61SXh2Da6LPAgMBAAECggEAI3NcBzUZVFJb+J4nfsGk/lgBlzl4C9mdPaOgXFXp41CBt1wLA/alaxQ+Ssn0PMrBb7XEe10TIAxuZylFjGYUT6FNbT7+0GQeQXixSMiEQxusnUJYw9I+esWgV9av5DtQRpJTGT52LrjaPL67Cd2l+dg9Jfz3HVCWoPsERNmMVUOHLpH3TqqmuKOMw4bW6JAfPGOMwfZ5Y1tETDHqNu7hdEn2VrgNTmq9xaPJn8Qnkum7frYmZBkfg6SarbEM9kMCPwdkmZa8U8197j8XtqANQ9XFsDVv7GI5V4vvg/+Kjuf5rE1iIVmbc043lPAL+Rs03KQoEursFH8mg7/agGLBYQKBgQD9czXOBSOIObZFZlLYBz47YAB8YA+YffTpG9HWu65Vk+hNyQfUdplilZUFF5fhI/zPPyMvpNjiB2PfTYX8ne9VoiVzE9GHAPq1LNeUJ+CG2NSiHrpbVOzQ8ULLCBUVNI28sqAoxANTTBSAqkX5U29mpzEATFGDTgViwoIG0DL+RwKBgQCVrmW0UI36An6pmBYxwsPgHCKrtPyfx/BCg40Bacj2whxJfO0p8s/26dArDDjeUsnCmJqlTyBz6JwOb/SOoi7GV2vVw7tJ1ADftWzCV6QUoqOWiJbdMPoKxhcERmrqTeqCC/Wij79n8KQXbv1n8ztUOIHF/RmVh1C/wQkWE2BTOQKBgQDcCGltsohme7QCDBNf+OnOIkpJsBvaB3/X4I8MHWP8Z6wF28EwcsY3ECWPhiwVCWkxg17IvhSMJl5OPr9T0Mk3Ts20WkBNNExzfbqqpPQIHbZ8CLFBGTl/K/UQzrN+9WEXsPvaaFF6v1INYcXd7tGIDR49ZARgOhvy4WqA/79FgQKBgCa4I1T+lYt7w7opPmyG3laF0K4sNkE63jrGft5DuBmk4t5bs5nrVsKffxrzoW5Zahmtkit7CYESRfQyH8gZyhHCoYF9jWAuuD8mVkj7lNVFsR2KncQAHF5XGbMgaB3OJACaCWOQ3cmMZVYufty5/bnumBtYOpsEku3XiHsubfd5AoGAOyvwdtlxrG3OfuAFcq9u8Pl/lqwKGQ1x7SBAiE0+rdPOVhmQeWNQDDgOLxn9nbeovoebs2kMUk10s8aVCTcpGYWRbEG4uKpKfJxlQcXPSbiyneFAUUygUgG5NJlFpHp5gdBabetAsdz0kH02dwXW3KNUMHvjzPCr01rNCAlV/ps=
  serverPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlDC3UHQB2hzO9v0YaOnjEMT8wR6WgYuxWWWhGPRgr3lF6rx4khH76dH5x4HL7IUU+ToZr+J0BE2y7Bs/ajpWX6WOhmyNuOuh6GeAyqKE+V6ae+JyEw4+U5quzi6Qlqre8vJoweD3XXtcrLUMUk6ziokUHtzpVyhD8+Ddi2DIXYjAEbjdr/URCJzfLDBzS3pyKmBf+8Is33XNuWbaHqA5WT3RDhY9QH4nxFPVxSN1OAehKo3xEy+0IinEkHCgd2fj5yz0mjV9LEXGQd8RMeNPv5Otoac9+VCZDx8kYKy3BJW2HHWRkYs6KHfZbpcpH9tSyvHpo7L96g+tUl4dg2uizwIDAQAB
  clientPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgZWEFb/MEecLlZaCgsEw/gZvTs5Kep9FKmWrCAt3HR2rG5VjBJWjTFq/vYr42si0w+fbhYNx0ZWsy1+nSFWUUJR0bo7Aj8SjsdPn8l+Znsf3oz2k/MzSVQyBucSv4pPRxahFdR24x882SGtceZWXfcXwohSNHaLkhwCgkkw8G7JQoH+3HggQQXzdsevawajS2ejerO4M7kjokFFzAoQqNB1bA2vjbbCdIo9AH3zKpHfEWoeMIfRjgY48i9ezaIiSrgpM/Z/T4rPm53UkuXlQSJ0ZN/5fKon0dJrhEYjF8KNWM27OswzQ+pJ1ijIn7bUmBozAQu9a3gwGDupBynpIyQIDAQAB
